// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/url/compilador/jflex/Reglas.flex

/* Seccion 1*/
package url.compilador;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\2\0\1\10\2\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\11\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\0\1\30\1\31\1\32\1\33"+
    "\1\34\10\32\1\35\1\36\1\37\1\32\1\40\10\32"+
    "\3\0\1\10\1\41\1\0\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\2\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\53\1\61\1\62\1\63\1\64"+
    "\1\65\1\53\1\66\1\53\1\67\1\70\1\0\1\71"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\3\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\2\20\1\21\1\22\1\23\1\24\1\25"+
    "\4\26\20\27\1\30\1\31\1\32\1\0\1\33\1\34"+
    "\1\35\1\36\1\0\1\37\1\0\1\40\1\41\1\42"+
    "\1\26\1\43\1\26\26\27\1\44\2\27\3\0\1\40"+
    "\1\45\1\0\1\46\1\26\37\27\1\0\1\47\1\40"+
    "\1\26\23\27\1\50\4\27\1\51\4\27\1\52\1\53"+
    "\1\54\1\55\2\27\1\47\1\26\2\27\1\56\3\27"+
    "\1\57\7\27\1\60\1\61\6\27\1\62\6\27\1\26"+
    "\1\27\1\63\1\27\1\64\4\27\1\65\17\27\1\26"+
    "\1\66\11\27\1\67\3\27\1\70\11\27\1\26\6\27"+
    "\1\71\1\72\1\73\1\74\1\75\3\27\1\76\1\77"+
    "\1\100\2\27\1\101\1\102\1\103\1\27\1\104\10\27"+
    "\1\105\3\27\1\106\5\27\1\107\1\27\1\110\1\27"+
    "\1\111\1\112\2\27\1\113\1\114\1\115\1\116\1\117"+
    "\3\27\1\120\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\72\0\72\0\72\0\164\0\72\0\256"+
    "\0\350\0\72\0\u0122\0\72\0\72\0\u015c\0\72\0\u0196"+
    "\0\72\0\u01d0\0\u020a\0\u0244\0\72\0\72\0\u027e\0\72"+
    "\0\u02b8\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e"+
    "\0\u0488\0\u04c2\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e"+
    "\0\u0658\0\u0692\0\u06cc\0\u0706\0\u0740\0\72\0\72\0\72"+
    "\0\350\0\350\0\72\0\72\0\72\0\u077a\0\u07b4\0\u07ee"+
    "\0\u0828\0\72\0\72\0\u0862\0\u032c\0\u089c\0\u08d6\0\u0910"+
    "\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0"+
    "\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c\0\u0c76\0\u0cb0"+
    "\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46\0\u0e80"+
    "\0\u0eba\0\u0ef4\0\u07ee\0\u07ee\0\u0f2e\0\u032c\0\u0f68\0\u0fa2"+
    "\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe\0\u1138\0\u1172"+
    "\0\u11ac\0\u11e6\0\u1220\0\u125a\0\u1294\0\u12ce\0\u1308\0\u1342"+
    "\0\u137c\0\u13b6\0\u13f0\0\u142a\0\u1464\0\u149e\0\u14d8\0\u1512"+
    "\0\u154c\0\u1586\0\u15c0\0\u15fa\0\u1634\0\u166e\0\u16a8\0\u077a"+
    "\0\u0f2e\0\u16e2\0\u171c\0\u1756\0\u1790\0\u17ca\0\u1804\0\u183e"+
    "\0\u1878\0\u18b2\0\u18ec\0\u1926\0\u1960\0\u199a\0\u19d4\0\u1a0e"+
    "\0\u1a48\0\u1a82\0\u1abc\0\u1af6\0\u1b30\0\u03da\0\u1b6a\0\u1ba4"+
    "\0\u1bde\0\u1c18\0\u03da\0\u1c52\0\u1c8c\0\u1cc6\0\u1d00\0\u03da"+
    "\0\u03da\0\u03da\0\u03da\0\u1d3a\0\u1d74\0\u0e80\0\u1dae\0\u1de8"+
    "\0\u1e22\0\u03da\0\u1e5c\0\u1e96\0\u1ed0\0\u03da\0\u1f0a\0\u1f44"+
    "\0\u1f7e\0\u1fb8\0\u1ff2\0\u202c\0\u2066\0\u03da\0\u03da\0\u20a0"+
    "\0\u20da\0\u2114\0\u214e\0\u2188\0\u21c2\0\u03da\0\u21fc\0\u2236"+
    "\0\u2270\0\u22aa\0\u22e4\0\u231e\0\u2358\0\u2392\0\u23cc\0\u2406"+
    "\0\u03da\0\u2440\0\u247a\0\u24b4\0\u24ee\0\u03da\0\u2528\0\u2562"+
    "\0\u259c\0\u25d6\0\u2610\0\u264a\0\u2684\0\u26be\0\u26f8\0\u2732"+
    "\0\u276c\0\u27a6\0\u27e0\0\u281a\0\u2854\0\u288e\0\u03da\0\u28c8"+
    "\0\u2902\0\u293c\0\u2976\0\u29b0\0\u29ea\0\u2a24\0\u2a5e\0\u2a98"+
    "\0\u03da\0\u2ad2\0\u2b0c\0\u2b46\0\u03da\0\u2b80\0\u2bba\0\u2bf4"+
    "\0\u2c2e\0\u2c68\0\u2ca2\0\u2cdc\0\u2d16\0\u2d50\0\u2d8a\0\u2dc4"+
    "\0\u2dfe\0\u2e38\0\u2e72\0\u2eac\0\u2ee6\0\u03da\0\u03da\0\u03da"+
    "\0\u03da\0\u03da\0\u2f20\0\u2f5a\0\u2f94\0\u03da\0\u03da\0\u03da"+
    "\0\u2fce\0\u3008\0\u03da\0\u03da\0\u03da\0\u3042\0\u032c\0\u307c"+
    "\0\u30b6\0\u30f0\0\u312a\0\u3164\0\u319e\0\u31d8\0\u3212\0\u03da"+
    "\0\u324c\0\u3286\0\u32c0\0\u03da\0\u32fa\0\u3334\0\u336e\0\u33a8"+
    "\0\u33e2\0\u03da\0\u341c\0\u03da\0\u3456\0\u03da\0\u03da\0\u3490"+
    "\0\u34ca\0\u03da\0\u03da\0\u03da\0\u03da\0\u03da\0\u3504\0\u353e"+
    "\0\u3578\0\u03da\0\u03da";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\5\33\1\34\1\35\1\33\1\2\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\36\1\44\1\45\1\36"+
    "\1\46\1\47\1\50\1\36\1\51\1\52\1\53\1\54"+
    "\1\36\1\55\2\36\1\56\1\57\74\0\1\4\115\0"+
    "\1\60\43\0\2\61\3\0\2\61\1\62\62\61\12\0"+
    "\1\63\73\0\1\64\73\0\1\65\66\0\1\66\4\0"+
    "\1\67\70\0\1\70\1\0\2\71\66\0\1\70\1\0"+
    "\2\24\75\0\1\72\71\0\1\73\64\0\2\33\5\0"+
    "\5\33\1\74\32\33\23\0\2\33\5\0\40\33\23\0"+
    "\2\33\5\0\10\33\1\75\27\33\23\0\2\33\5\0"+
    "\31\33\1\76\6\33\23\0\2\36\5\0\40\36\23\0"+
    "\2\36\5\0\27\36\1\77\10\36\23\0\2\36\5\0"+
    "\12\36\1\100\11\36\1\101\2\36\1\102\10\36\23\0"+
    "\2\36\5\0\16\36\1\103\21\36\23\0\2\36\5\0"+
    "\24\36\1\104\1\36\1\105\3\36\1\106\3\36\1\107"+
    "\1\36\23\0\2\36\5\0\12\36\1\110\25\36\23\0"+
    "\2\36\5\0\12\36\1\111\25\36\23\0\2\36\5\0"+
    "\26\36\1\112\11\36\23\0\2\36\5\0\16\36\1\113"+
    "\10\36\1\114\10\36\23\0\2\36\5\0\16\36\1\115"+
    "\3\36\1\116\15\36\23\0\2\36\5\0\34\36\1\117"+
    "\3\36\23\0\2\36\5\0\31\36\1\120\2\36\1\121"+
    "\3\36\23\0\2\36\5\0\12\36\1\122\3\36\1\123"+
    "\21\36\23\0\2\36\5\0\16\36\1\124\3\36\1\125"+
    "\15\36\23\0\2\36\5\0\12\36\1\126\25\36\23\0"+
    "\2\36\5\0\16\36\1\127\21\36\2\0\2\66\1\130"+
    "\1\0\1\131\6\66\1\132\56\66\2\67\3\0\65\67"+
    "\21\0\1\133\1\134\66\0\1\135\1\0\2\71\70\0"+
    "\2\33\5\0\3\33\1\136\34\33\23\0\2\33\5\0"+
    "\22\33\1\137\15\33\23\0\2\36\5\0\24\36\1\140"+
    "\13\36\23\0\2\36\5\0\15\36\1\141\22\36\23\0"+
    "\2\36\5\0\12\36\1\142\25\36\23\0\2\36\5\0"+
    "\26\36\1\143\3\36\1\144\5\36\23\0\2\36\5\0"+
    "\14\36\1\145\15\36\1\146\2\36\1\147\2\36\23\0"+
    "\2\36\5\0\22\36\1\150\15\36\23\0\2\36\5\0"+
    "\33\36\1\151\4\36\23\0\2\36\5\0\14\36\1\152"+
    "\23\36\23\0\2\36\5\0\33\36\1\153\4\36\23\0"+
    "\2\36\5\0\24\36\1\154\13\36\23\0\2\36\5\0"+
    "\14\36\1\155\23\36\23\0\2\36\5\0\14\36\1\156"+
    "\15\36\1\157\5\36\23\0\2\36\5\0\16\36\1\160"+
    "\21\36\23\0\2\36\5\0\20\36\1\161\17\36\23\0"+
    "\2\36\5\0\33\36\1\162\4\36\23\0\2\36\5\0"+
    "\16\36\1\163\21\36\23\0\2\36\5\0\16\36\1\164"+
    "\5\36\1\165\13\36\23\0\2\36\5\0\22\36\1\166"+
    "\4\36\1\167\10\36\23\0\2\36\5\0\13\36\1\170"+
    "\24\36\23\0\2\36\5\0\22\36\1\171\15\36\23\0"+
    "\2\36\5\0\12\36\1\172\25\36\23\0\2\36\5\0"+
    "\26\36\1\173\11\36\23\0\2\36\5\0\26\36\1\174"+
    "\11\36\23\0\2\36\5\0\26\36\1\175\11\36\23\0"+
    "\2\36\5\0\31\36\1\176\6\36\2\0\2\130\3\0"+
    "\6\130\1\177\61\130\2\0\6\130\1\177\56\130\2\66"+
    "\1\130\1\0\1\131\6\66\1\132\4\66\1\200\51\66"+
    "\21\0\2\201\70\0\2\33\5\0\26\33\1\202\11\33"+
    "\23\0\2\36\5\0\16\36\1\203\21\36\23\0\2\36"+
    "\5\0\16\36\1\204\21\36\23\0\2\36\5\0\32\36"+
    "\1\205\5\36\23\0\2\36\5\0\32\36\1\206\5\36"+
    "\23\0\2\36\5\0\16\36\1\207\21\36\23\0\2\36"+
    "\5\0\31\36\1\210\6\36\23\0\2\36\5\0\15\36"+
    "\1\211\15\36\1\212\4\36\23\0\2\36\5\0\27\36"+
    "\1\213\10\36\23\0\2\36\5\0\25\36\1\214\12\36"+
    "\23\0\2\36\5\0\16\36\1\215\10\36\1\216\10\36"+
    "\23\0\2\36\5\0\31\36\1\217\6\36\23\0\2\36"+
    "\5\0\22\36\1\220\15\36\23\0\2\36\5\0\32\36"+
    "\1\221\5\36\23\0\2\36\5\0\16\36\1\222\21\36"+
    "\23\0\2\36\5\0\24\36\1\223\4\36\1\224\6\36"+
    "\23\0\2\36\5\0\33\36\1\225\4\36\23\0\2\36"+
    "\5\0\31\36\1\226\6\36\23\0\2\36\5\0\12\36"+
    "\1\227\25\36\23\0\2\36\5\0\27\36\1\230\10\36"+
    "\23\0\2\36\5\0\26\36\1\231\11\36\23\0\2\36"+
    "\5\0\35\36\1\232\2\36\23\0\2\36\5\0\27\36"+
    "\1\233\10\36\23\0\2\36\5\0\35\36\1\234\2\36"+
    "\23\0\2\36\5\0\30\36\1\235\2\36\1\236\4\36"+
    "\23\0\2\36\5\0\24\36\1\237\13\36\23\0\2\36"+
    "\5\0\37\36\1\240\23\0\2\36\5\0\24\36\1\241"+
    "\13\36\23\0\2\36\5\0\27\36\1\242\10\36\23\0"+
    "\2\36\5\0\27\36\1\243\10\36\23\0\2\36\5\0"+
    "\20\36\1\244\17\36\23\0\2\36\5\0\15\36\1\245"+
    "\22\36\2\0\2\130\3\0\6\130\1\177\4\130\1\246"+
    "\51\130\21\0\2\33\5\0\14\33\1\247\23\33\23\0"+
    "\2\36\5\0\12\36\1\250\25\36\23\0\2\36\5\0"+
    "\26\36\1\251\11\36\23\0\2\36\5\0\16\36\1\252"+
    "\21\36\23\0\2\36\5\0\33\36\1\253\4\36\23\0"+
    "\2\36\5\0\26\36\1\254\11\36\23\0\2\36\5\0"+
    "\16\36\1\255\21\36\23\0\2\36\5\0\16\36\1\256"+
    "\21\36\23\0\2\36\5\0\31\36\1\257\6\36\23\0"+
    "\2\36\5\0\24\36\1\260\13\36\23\0\2\36\5\0"+
    "\22\36\1\261\15\36\23\0\2\36\5\0\31\36\1\262"+
    "\6\36\23\0\2\36\5\0\26\36\1\263\11\36\23\0"+
    "\2\36\5\0\22\36\1\264\15\36\23\0\2\36\5\0"+
    "\16\36\1\265\21\36\23\0\2\36\5\0\27\36\1\266"+
    "\10\36\23\0\2\36\5\0\31\36\1\267\6\36\23\0"+
    "\2\36\5\0\34\36\1\270\3\36\23\0\2\36\5\0"+
    "\16\36\1\271\21\36\23\0\2\36\5\0\12\36\1\272"+
    "\25\36\23\0\2\36\5\0\31\36\1\273\6\36\23\0"+
    "\2\36\5\0\15\36\1\274\22\36\23\0\2\36\5\0"+
    "\33\36\1\275\4\36\23\0\2\36\5\0\27\36\1\276"+
    "\10\36\23\0\2\36\5\0\12\36\1\277\25\36\23\0"+
    "\2\36\5\0\22\36\1\300\15\36\23\0\2\36\5\0"+
    "\16\36\1\301\21\36\23\0\2\36\5\0\22\36\1\302"+
    "\15\36\23\0\2\36\5\0\16\36\1\303\21\36\23\0"+
    "\2\36\5\0\12\36\1\304\25\36\23\0\2\33\5\0"+
    "\22\33\1\305\15\33\23\0\2\36\5\0\26\36\1\306"+
    "\11\36\23\0\2\36\5\0\12\36\1\307\25\36\23\0"+
    "\2\36\5\0\31\36\1\310\6\36\23\0\2\36\5\0"+
    "\27\36\1\311\10\36\23\0\2\36\5\0\25\36\1\312"+
    "\12\36\23\0\2\36\5\0\34\36\1\313\3\36\23\0"+
    "\2\36\5\0\35\36\1\314\2\36\23\0\2\36\5\0"+
    "\26\36\1\315\11\36\23\0\2\36\5\0\27\36\1\316"+
    "\10\36\23\0\2\36\5\0\14\36\1\317\23\36\23\0"+
    "\2\36\5\0\13\36\1\320\24\36\23\0\2\36\5\0"+
    "\26\36\1\321\11\36\23\0\2\36\5\0\22\36\1\322"+
    "\15\36\23\0\2\36\5\0\25\36\1\323\12\36\23\0"+
    "\2\36\5\0\26\36\1\324\11\36\23\0\2\36\5\0"+
    "\22\36\1\325\15\36\23\0\2\36\5\0\27\36\1\326"+
    "\10\36\23\0\2\36\5\0\31\36\1\327\6\36\23\0"+
    "\2\36\5\0\15\36\1\330\22\36\23\0\2\36\5\0"+
    "\16\36\1\331\21\36\23\0\2\36\5\0\20\36\1\332"+
    "\17\36\23\0\2\36\5\0\14\36\1\333\23\36\23\0"+
    "\2\36\5\0\26\36\1\334\11\36\23\0\2\36\5\0"+
    "\15\36\1\335\22\36\23\0\2\33\5\0\30\33\1\336"+
    "\7\33\23\0\2\36\5\0\27\36\1\337\10\36\23\0"+
    "\2\36\5\0\1\340\37\36\23\0\2\36\5\0\34\36"+
    "\1\341\3\36\23\0\2\36\5\0\16\36\1\342\21\36"+
    "\23\0\2\36\5\0\14\36\1\343\23\36\23\0\2\36"+
    "\5\0\16\36\1\344\21\36\23\0\2\36\5\0\12\36"+
    "\1\345\25\36\23\0\2\36\5\0\16\36\1\346\21\36"+
    "\23\0\2\36\5\0\22\36\1\347\15\36\23\0\2\36"+
    "\5\0\15\36\1\350\22\36\23\0\2\36\5\0\31\36"+
    "\1\351\6\36\23\0\2\36\5\0\16\36\1\352\21\36"+
    "\23\0\2\36\5\0\14\36\1\353\23\36\23\0\2\36"+
    "\5\0\33\36\1\354\4\36\23\0\2\36\5\0\32\36"+
    "\1\355\5\36\23\0\2\36\5\0\12\36\1\356\25\36"+
    "\23\0\2\36\5\0\12\36\1\357\14\36\1\360\10\36"+
    "\23\0\2\36\5\0\15\36\1\361\22\36\23\0\2\36"+
    "\5\0\22\36\1\362\15\36\23\0\2\36\5\0\12\36"+
    "\1\363\14\36\1\364\10\36\23\0\2\36\5\0\33\36"+
    "\1\365\4\36\23\0\2\36\5\0\16\36\1\366\21\36"+
    "\23\0\2\33\5\0\12\33\1\367\25\33\23\0\2\36"+
    "\5\0\1\36\1\370\2\36\1\371\3\36\1\372\27\36"+
    "\23\0\2\36\5\0\14\36\1\373\23\36\23\0\2\36"+
    "\5\0\26\36\1\374\11\36\23\0\2\36\5\0\33\36"+
    "\1\375\4\36\23\0\2\36\5\0\31\36\1\376\6\36"+
    "\23\0\2\36\5\0\31\36\1\377\6\36\23\0\2\36"+
    "\5\0\32\36\1\u0100\5\36\23\0\2\36\5\0\31\36"+
    "\1\u0101\6\36\23\0\2\36\5\0\16\36\1\u0102\21\36"+
    "\23\0\2\36\5\0\26\36\1\u0103\11\36\23\0\2\36"+
    "\5\0\22\36\1\u0104\15\36\23\0\2\36\5\0\25\36"+
    "\1\u0105\12\36\23\0\2\36\5\0\32\36\1\u0106\5\36"+
    "\23\0\2\36\5\0\32\36\1\u0107\5\36\23\0\2\36"+
    "\5\0\32\36\1\u0108\5\36\23\0\2\36\5\0\12\36"+
    "\1\u0109\25\36\23\0\2\36\5\0\15\36\1\u010a\22\36"+
    "\23\0\2\36\5\0\32\36\1\u010b\5\36\23\0\2\36"+
    "\5\0\32\36\1\u010c\5\36\23\0\2\36\5\0\16\36"+
    "\1\u010d\21\36\23\0\2\36\5\0\31\36\1\u010e\6\36"+
    "\23\0\2\33\5\0\24\33\1\u010f\13\33\23\0\2\36"+
    "\5\0\27\36\1\u0110\10\36\23\0\2\36\5\0\26\36"+
    "\1\u0111\11\36\23\0\2\36\5\0\16\36\1\u0112\21\36"+
    "\23\0\2\36\5\0\33\36\1\u0113\4\36\23\0\2\36"+
    "\5\0\33\36\1\u0114\4\36\23\0\2\36\5\0\27\36"+
    "\1\u0115\10\36\23\0\2\36\5\0\33\36\1\u0116\4\36"+
    "\23\0\2\36\5\0\12\36\1\u0117\25\36\23\0\2\36"+
    "\5\0\27\36\1\u0118\10\36\23\0\2\36\5\0\15\36"+
    "\1\u0119\22\36\23\0\2\36\5\0\12\36\1\u011a\14\36"+
    "\1\u011b\10\36\23\0\2\36\5\0\27\36\1\u011c\10\36"+
    "\23\0\2\36\5\0\24\36\1\u011d\13\36\23\0\2\36"+
    "\5\0\33\36\1\u011e\4\36\23\0\2\36\5\0\12\36"+
    "\1\u011f\25\36\23\0\2\36\5\0\27\36\1\u0120\10\36"+
    "\23\0\2\36\5\0\12\36\1\u0121\25\36\23\0\2\36"+
    "\5\0\31\36\1\u0122\6\36\23\0\2\36\5\0\12\36"+
    "\1\u0123\25\36\23\0\2\36\5\0\31\36\1\u0124\6\36"+
    "\23\0\2\36\5\0\16\36\1\u0125\21\36\23\0\2\36"+
    "\5\0\32\36\1\u0126\5\36\23\0\2\36\5\0\32\36"+
    "\1\u0127\5\36\23\0\2\36\5\0\16\36\1\u0128\21\36"+
    "\23\0\2\36\5\0\16\36\1\u0129\21\36\23\0\2\36"+
    "\5\0\24\36\1\u012a\13\36\23\0\2\36\5\0\31\36"+
    "\1\u012b\6\36\23\0\2\36\5\0\31\36\1\u012c\6\36"+
    "\23\0\2\36\5\0\31\36\1\u012d\6\36\23\0\2\36"+
    "\5\0\32\36\1\u012e\5\36\23\0\2\36\5\0\12\36"+
    "\1\u012f\25\36\23\0\2\36\5\0\31\36\1\u0130\6\36"+
    "\23\0\2\36\5\0\26\36\1\u0131\11\36\23\0\2\36"+
    "\5\0\27\36\1\u0132\10\36\23\0\2\36\5\0\27\36"+
    "\1\u0133\10\36\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[13746];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\11\1\1\1\11\2\1\1\11\1\1\2\11"+
    "\1\1\1\11\1\1\1\11\3\1\2\11\1\1\1\11"+
    "\25\1\3\11\1\0\1\1\3\11\1\0\1\1\1\0"+
    "\1\1\2\11\34\1\3\0\2\1\1\0\41\1\1\0"+
    "\264\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[307];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    /* Funcion para pasar los errores al archivo ERRORES.txt*/
    void LexLuthorErr(String Token, String Valor)
    {
        try {
            char enter=13;
            String regreso=Token+"  "+Valor;
            RandomAccessFile errores= new RandomAccessFile("ERRORES.txt","rw");
            errores.seek(errores.length());
            errores.writeBytes(regreso);
            errores.writeChar(enter);
            errores.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /* Funcion para pasar los tokens al archivo LEXEMAS.txt*/
    void LexLuthor(String Token, String Valor)
    {
        try {
            char enter=13;
            String regreso=Token+"  "+Valor;
            RandomAccessFile traductor= new RandomAccessFile("LEXEMAS.txt","rw");
            traductor.seek(traductor.length());
            traductor.writeBytes(regreso);
            traductor.writeChar(enter);
            traductor.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
          /* Se inicializa el txt de LEXEMAS.txt, se sobreescribe el archivo para dejarlo vacio*/
       try {
            RandomAccessFile traductor= new RandomAccessFile("LEXEMAS.txt","rw");
            traductor.setLength(0);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Se inicializa el txt de ERRORES.txt, se sobreescribe el archivo para dejarlo vacio*/
        try {
            RandomAccessFile errores= new RandomAccessFile("ERRORES.txt","rw");
            errores.setLength(0);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Lexico.class.getName()).log(Level.SEVERE, null, ex);
        }

    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("error: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthorErr("ERROR ---- ",yytext());
            }
            // fall through
          case 82: break;
          case 2:
            { System.out.println("encontre un tabulador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    return new Symbol (sym.TABULADOR);
            }
            // fall through
          case 83: break;
          case 3:
            { System.out.println("encontre un ENTER: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("ENTER ----- ",yytext());
    return new Symbol (sym.ENTER);
            }
            // fall through
          case 84: break;
          case 4:
            { System.out.print(yytext());
            }
            // fall through
          case 85: break;
          case 5:
            { System.out.println("encontre un espacio en blanco: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
            }
            // fall through
          case 86: break;
          case 6:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("COMILLAS ----- ",yytext());
    return new Symbol (sym.COMILLAS);
            }
            // fall through
          case 87: break;
          case 7:
            { System.out.println("encontre un operador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("OPERADOR ----- ",yytext());
    return new Symbol (sym.OPERADORA);
            }
            // fall through
          case 88: break;
          case 8:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PARENTESIS1 ----- ",yytext());
    return new Symbol (sym.PARENTESIS1);
            }
            // fall through
          case 89: break;
          case 9:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PARENTESIS2 ----- ",yytext());
    return new Symbol (sym.PARENTESIS2);
            }
            // fall through
          case 90: break;
          case 10:
            { System.out.println("encontre un operador de multiplicacion: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MULTIPLICACION ----- ",yytext());
    return new Symbol (sym.MULTIPLICACION);
            }
            // fall through
          case 91: break;
          case 11:
            { System.out.println("encontre un operador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MAS ----- ",yytext());
    return new Symbol (sym.MAS);
            }
            // fall through
          case 92: break;
          case 12:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("COMA ----- ",yytext());
    return new Symbol (sym.COMA);
            }
            // fall through
          case 93: break;
          case 13:
            { System.out.println("encontre un operador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MENOS ----- ",yytext());
    return new Symbol (sym.MENOS);
            }
            // fall through
          case 94: break;
          case 14:
            { System.out.println("encontre un punto: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PUNTO ----- ",yytext());
    return new Symbol (sym.PUNTO);
            }
            // fall through
          case 95: break;
          case 15:
            { System.out.println("encontre un operador de division: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("DIVISION ----- ",yytext());
    return new Symbol (sym.DIVISION);
            }
            // fall through
          case 96: break;
          case 16:
            { System.out.println("encontre un numero: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("NUMEROENTERO ----- ",yytext());
    return new Symbol (sym.NUMEROENTERO);
            }
            // fall through
          case 97: break;
          case 17:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("DOSPUNTOS ----- ",yytext());
    return new Symbol (sym.DOSPUNTOS);
            }
            // fall through
          case 98: break;
          case 18:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PUNTOCOMA ----- ",yytext());
    return new Symbol (sym.PUNTOCOMA);
            }
            // fall through
          case 99: break;
          case 19:
            { System.out.println("encontre un operador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MENOR ----- ",yytext());
    return new Symbol (sym.MENOR);
            }
            // fall through
          case 100: break;
          case 20:
            { System.out.println("encontre un operador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("IGUAL ----- ",yytext());
    return new Symbol (sym.IGUAL);
            }
            // fall through
          case 101: break;
          case 21:
            { System.out.println("encontre un operador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MAYOR ----- ",yytext());
    return new Symbol (sym.MAYOR);
            }
            // fall through
          case 102: break;
          case 22:
            { System.out.println("encontre una var de Metodo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("ID_METODO ----- ",yytext());
    return new Symbol (sym.ID_METODO);
            }
            // fall through
          case 103: break;
          case 23:
            { System.out.println("encontre una variable: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("ID ----- ",yytext());
    return new Symbol (sym.ID);
            }
            // fall through
          case 104: break;
          case 24:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("LLAVE1 ----- ",yytext());
    return new Symbol (sym.LLAVE1);
            }
            // fall through
          case 105: break;
          case 25:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("LLAVE2 ----- ",yytext());
    return new Symbol (sym.LLAVE2);
            }
            // fall through
          case 106: break;
          case 26:
            { System.out.println("encontre un operador: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("NOIGUAL ----- ",yytext());
    return new Symbol (sym.NOIGUAL);
            }
            // fall through
          case 107: break;
          case 27:
            { System.out.println("encontre una cadena: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("CADENA ----- ",yytext());
    return new Symbol (sym.CADENA);
            }
            // fall through
          case 108: break;
          case 28:
            { System.out.println("encontre un signo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("USOMETODO ----- ",yytext());
    return new Symbol (sym.USOMETODO);
            }
            // fall through
          case 109: break;
          case 29:
            { System.out.println("encontre un incremento: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("INCREMENTO ----- ",yytext());
    return new Symbol (sym.INCREMENTO);
            }
            // fall through
          case 110: break;
          case 30:
            { System.out.println("encontre un decremento: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("DECREMENTO ----- ",yytext());
    return new Symbol (sym.DECREMENTO);
            }
            // fall through
          case 111: break;
          case 31:
            { System.out.println("encontre un comentario A: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("COMENTARIOA ----- ",yytext());
    return new Symbol (sym.COMENTARIOA);
            }
            // fall through
          case 112: break;
          case 32:
            { System.out.println("encontre una Numero Malo: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthorErr("NUMEROMALO ----- ",yytext());
            }
            // fall through
          case 113: break;
          case 33:
            { System.out.println("encontre un mayorIgual: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MENORIGUAL ----- ",yytext());
    return new Symbol (sym.MENORIGUAL);
            }
            // fall through
          case 114: break;
          case 34:
            { System.out.println("encontre un mayorIgual: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MAYORIGUAL ----- ",yytext());
    return new Symbol (sym.MAYORIGUAL);
            }
            // fall through
          case 115: break;
          case 35:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("OR ----- ",yytext());
    return new Symbol (sym.OR);
            }
            // fall through
          case 116: break;
          case 36:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("SI ----- ",yytext());
    return new Symbol (sym.SI);
            }
            // fall through
          case 117: break;
          case 37:
            { System.out.println("encontre una real: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("REAL ----- ",yytext());
    return new Symbol (sym.REAL);
            }
            // fall through
          case 118: break;
          case 38:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("AND ----- ",yytext());
    return new Symbol (sym.AND);
            }
            // fall through
          case 119: break;
          case 39:
            { System.out.println("encontre un comentario B: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("COMENTARIOB ----- ",yytext());
    return new Symbol (sym.COMENTARIOB);
            }
            // fall through
          case 120: break;
          case 40:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("LEER ----- ",yytext());
    return new Symbol (sym.LEER);
            }
            // fall through
          case 121: break;
          case 41:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("NULO ----- ",yytext());
    return new Symbol (sym.NULO);
            }
            // fall through
          case 122: break;
          case 42:
            { System.out.println("encontre una función especial (matemática): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("RAIZ ----- ",yytext());
    return new Symbol (sym.RAIZ);
            }
            // fall through
          case 123: break;
          case 43:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("REAL ----- ",yytext());
    return new Symbol (sym.REALR);
            }
            // fall through
          case 124: break;
          case 44:
            { System.out.println("encontre una función especial (matemática): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("SENO ----- ",yytext());
    return new Symbol (sym.SENO);
            }
            // fall through
          case 125: break;
          case 45:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("SINO ----- ",yytext());
    return new Symbol (sym.SINO);
            }
            // fall through
          case 126: break;
          case 46:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("CLASE ----- ",yytext());
    return new Symbol (sym.CLASE);
            }
            // fall through
          case 127: break;
          case 47:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("DESDE ----- ",yytext());
    return new Symbol (sym.DESDE);
            }
            // fall through
          case 128: break;
          case 48:
            { System.out.println("encontre un falso ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("FALSO ----- ",yytext());
    return new Symbol (sym.FALSO);
            }
            // fall through
          case 129: break;
          case 49:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("HACER ----- ",yytext());
    return new Symbol (sym.HACER);
            }
            // fall through
          case 130: break;
          case 50:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("NUEVO ----- ",yytext());
    return new Symbol (sym.NUEVO);
            }
            // fall through
          case 131: break;
          case 51:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("CADENA ----- ",yytext());
    return new Symbol (sym.CADENAR);
            }
            // fall through
          case 132: break;
          case 52:
            { System.out.println("encontre una función especial (matemática): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("COSENO ----- ",yytext());
    return new Symbol (sym.COSENO);
            }
            // fall through
          case 133: break;
          case 53:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("ENTERO ----- ",yytext());
    return new Symbol (sym.ENTEROR);
            }
            // fall through
          case 134: break;
          case 54:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("BOOLEANO ----- ",yytext());
    return new Symbol (sym.BOOLEANOR);
            }
            // fall through
          case 135: break;
          case 55:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("INCLUIR ----- ",yytext());
    return new Symbol (sym.INCLUIR);
            }
            // fall through
          case 136: break;
          case 56:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("METODOS ----- ",yytext());
    return new Symbol (sym.METODOS);
            }
            // fall through
          case 137: break;
          case 57:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("DEVOLVER ----- ",yytext());
    return new Symbol (sym.DEVOLVER);
            }
            // fall through
          case 138: break;
          case 58:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("ELIMINAR ----- ",yytext());
    return new Symbol (sym.ELIMINAR);
            }
            // fall through
          case 139: break;
          case 59:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("ENTONCES ----- ",yytext());
    return new Symbol (sym.ENTONCES);
            }
            // fall through
          case 140: break;
          case 60:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("ESCRIBIR ----- ",yytext());
    return new Symbol (sym.ESCRIBIR);
            }
            // fall through
          case 141: break;
          case 61:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("EXTIENDE ----- ",yytext());
    return new Symbol (sym.EXTIENDE);
            }
            // fall through
          case 142: break;
          case 62:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("MIENTRAS ----- ",yytext());
    return new Symbol (sym.MIENTRAS);
            }
            // fall through
          case 143: break;
          case 63:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PRIVADAS ----- ",yytext());
    return new Symbol (sym.PRIVADAS);
            }
            // fall through
          case 144: break;
          case 64:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PRIVADOS ----- ",yytext());
    return new Symbol (sym.PRIVADOS);
            }
            // fall through
          case 145: break;
          case 65:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PUBLICAS ----- ",yytext());
    return new Symbol (sym.PUBLICAS);
            }
            // fall through
          case 146: break;
          case 66:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PUBLICOS ----- ",yytext());
    return new Symbol (sym.PUBLICOS);
            }
            // fall through
          case 147: break;
          case 67:
            { System.out.println("encontre una función especial (matemática): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("TANGENTE ----- ",yytext());
    return new Symbol (sym.TANGENTE);
            }
            // fall through
          case 148: break;
          case 68:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PRINCIPAL ----- ",yytext());
    return new Symbol (sym.PRINCIPAL);
            }
            // fall through
          case 149: break;
          case 69:
            { System.out.println("encontre una función especial (matemática): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("LOGARITMO ----- ",yytext());
    return new Symbol (sym.LOGARITMO);
            }
            // fall through
          case 150: break;
          case 70:
            { System.out.println("encontre un verdadero ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("VERDADERO ----- ",yytext());
    return new Symbol (sym.VERDADERO);
            }
            // fall through
          case 151: break;
          case 71:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("DESTRUCTOR ----- ",yytext());
    return new Symbol (sym.DESTRUCTOR);
            }
            // fall through
          case 152: break;
          case 72:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("INSTANCIAR ----- ",yytext());
    return new Symbol (sym.INSTANCIAR);
            }
            // fall through
          case 153: break;
          case 73:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PROTEGIDAS ----- ",yytext());
    return new Symbol (sym.PROTEGIDAS);
            }
            // fall through
          case 154: break;
          case 74:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PROTEGIDOS ----- ",yytext());
    return new Symbol (sym.PROTEGIDOS);
            }
            // fall through
          case 155: break;
          case 75:
            { System.out.println("encontre una función especial (conversion): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("CADENAAREAL ----- ",yytext());
    return new Symbol (sym.CADENAAREAL);
            }
            // fall through
          case 156: break;
          case 76:
            { System.out.println("encontre una palabra reservada ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("CONSTRUCTOR ----- ",yytext());
    return new Symbol (sym.CONSTRUCTOR);
            }
            // fall through
          case 157: break;
          case 77:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("DECREMENTAR ----- ",yytext());
    return new Symbol (sym.DECREMENTAR);
            }
            // fall through
          case 158: break;
          case 78:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("INCREMENTAR ----- ",yytext());
    return new Symbol (sym.INCREMENTAR);
            }
            // fall through
          case 159: break;
          case 79:
            { System.out.println("encontre una palabra reservada: ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("PROPIEDADES ----- ",yytext());
    return new Symbol (sym.PROPIEDADES);
            }
            // fall through
          case 160: break;
          case 80:
            { System.out.println("encontre una función especial (conversion): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("CADENAAENTERO ----- ",yytext());
    return new Symbol (sym.CADENAAENTERO);
            }
            // fall through
          case 161: break;
          case 81:
            { System.out.println("encontre una función especial (conversion): ["+ yytext() + "] en linea: " 
    + (yyline+1)  + " columna: " + (yycolumn+1));
    LexLuthor("CADENAABOOLEANO ----- ",yytext());
    return new Symbol (sym.CADENAABOOLEANO);
            }
            // fall through
          case 162: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexico scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexico(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
