
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package url.compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ELIMINAR = 17;
  public static final int COMILLAS = 54;
  public static final int ENTEROR = 26;
  public static final int REAL = 63;
  public static final int PUBLICAS = 33;
  public static final int LLAVE2 = 53;
  public static final int LLAVE1 = 52;
  public static final int COMENTARIOB = 4;
  public static final int VERDADERO = 5;
  public static final int COMENTARIOA = 3;
  public static final int MAYOR = 61;
  public static final int PROPIEDADES = 31;
  public static final int DECREMENTAR = 73;
  public static final int SI = 7;
  public static final int CONSTRUCTOR = 18;
  public static final int TABULADOR = 55;
  public static final int LEER = 9;
  public static final int OPERADORA = 57;
  public static final int ID_METODO = 66;
  public static final int FALSO = 6;
  public static final int PRIVADOS = 37;
  public static final int CADENAAENTERO = 44;
  public static final int HACER = 15;
  public static final int INCREMENTO = 70;
  public static final int COMA = 49;
  public static final int CADENAABOOLEANO = 46;
  public static final int IGUAL = 56;
  public static final int CLASE = 24;
  public static final int PRIVADAS = 34;
  public static final int DOSPUNTOS = 47;
  public static final int PROTEGIDOS = 38;
  public static final int INCLUIR = 23;
  public static final int BOOLEANOR = 29;
  public static final int REALR = 27;
  public static final int COSENO = 40;
  public static final int DECREMENTO = 69;
  public static final int MENOS = 59;
  public static final int MENOR = 60;
  public static final int MAS = 58;
  public static final int NULO = 30;
  public static final int EOF = 0;
  public static final int MIENTRAS = 13;
  public static final int PUNTO = 76;
  public static final int DEVOLVER = 14;
  public static final int MENORIGUAL = 68;
  public static final int TANGENTE = 41;
  public static final int PRINCIPAL = 22;
  public static final int DESTRUCTOR = 19;
  public static final int OR = 21;
  public static final int error = 1;
  public static final int PUBLICOS = 36;
  public static final int USOMETODO = 75;
  public static final int ENTER = 74;
  public static final int CADENAR = 28;
  public static final int RAIZ = 43;
  public static final int ID = 65;
  public static final int ENTONCES = 11;
  public static final int SINO = 10;
  public static final int PROTEGIDAS = 35;
  public static final int EXTIENDE = 25;
  public static final int NUMEROENTERO = 64;
  public static final int PUNTOCOMA = 48;
  public static final int INSTANCIAR = 16;
  public static final int LOGARITMO = 42;
  public static final int INCREMENTAR = 72;
  public static final int NOIGUAL = 62;
  public static final int CADENA = 2;
  public static final int MAYORIGUAL = 67;
  public static final int METODOS = 32;
  public static final int SENO = 39;
  public static final int PARENTESIS2 = 51;
  public static final int PARENTESIS1 = 50;
  public static final int ESCRIBIR = 8;
  public static final int AND = 20;
  public static final int CADENAAREAL = 45;
  public static final int NUEVO = 71;
  public static final int DESDE = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "COMENTARIOA",
  "COMENTARIOB",
  "VERDADERO",
  "FALSO",
  "SI",
  "ESCRIBIR",
  "LEER",
  "SINO",
  "ENTONCES",
  "DESDE",
  "MIENTRAS",
  "DEVOLVER",
  "HACER",
  "INSTANCIAR",
  "ELIMINAR",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "AND",
  "OR",
  "PRINCIPAL",
  "INCLUIR",
  "CLASE",
  "EXTIENDE",
  "ENTEROR",
  "REALR",
  "CADENAR",
  "BOOLEANOR",
  "NULO",
  "PROPIEDADES",
  "METODOS",
  "PUBLICAS",
  "PRIVADAS",
  "PROTEGIDAS",
  "PUBLICOS",
  "PRIVADOS",
  "PROTEGIDOS",
  "SENO",
  "COSENO",
  "TANGENTE",
  "LOGARITMO",
  "RAIZ",
  "CADENAAENTERO",
  "CADENAAREAL",
  "CADENAABOOLEANO",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "COMA",
  "PARENTESIS1",
  "PARENTESIS2",
  "LLAVE1",
  "LLAVE2",
  "COMILLAS",
  "TABULADOR",
  "IGUAL",
  "OPERADORA",
  "MAS",
  "MENOS",
  "MENOR",
  "MAYOR",
  "NOIGUAL",
  "REAL",
  "NUMEROENTERO",
  "ID",
  "ID_METODO",
  "MAYORIGUAL",
  "MENORIGUAL",
  "DECREMENTO",
  "INCREMENTO",
  "NUEVO",
  "INCREMENTAR",
  "DECREMENTAR",
  "ENTER",
  "USOMETODO",
  "PUNTO"
  };
}

